app:
  name: app
  env: local
  locale: en

server:
  host: 127.0.0.1
  port: 8000

zap:
  path: ./storage/logs/app.log
  level: debug
  max-size: 100
  max-backups: 7
  max-age: 30

gorm:
  data-sources:
    - id: mysql
      driver: mysql
      dsn: "root:root@tcp(127.0.0.1:3306)/app?charset=utf8mb4&parseTime=True&loc=Local"
      max-idle-conns: 10
      max-open-conns: 100
      conn-max-lifetime: 60
      slaves:
        - "root:root@tcp(127.0.0.1:3306)/app?charset=utf8mb4&parseTime=True&loc=Local"
  log:
    level: info
    slow-threshold: 300

jwt:
  issuer: app
  ttl: 21600
  algo: HS256
  secret:
