// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"app/internal/config"
	"app/internal/module/abouts"
	"app/internal/module/users"
	"app/internal/pkg/http"
	"app/internal/routes"
	"app/pkg/provider"
	"app/pkg/server"
)

// Injectors from wire.go:

func wireServer(conf config.Config) (*server.Server, func(), error) {
	logger, cleanup := provider.NewZapLogger()
	translator := provider.NewTranslator()
	json := http.NewJSON(translator)
	aboutController := abouts.NewAboutController(json, conf)
	dataSources, cleanup2 := provider.NewGORMDataSources(logger)
	userRepository := users.NewUserRepository(dataSources)
	userService := users.NewUserService(logger, userRepository)
	userController := users.NewUserController(json, userService)
	apiRouting := routes.NewAPIRouting(logger, json, aboutController, userController)
	ginxRoutes := routes.New(apiRouting)
	engine := provider.NewGin(logger, ginxRoutes)
	serverServer := provider.NewServer(engine)
	return serverServer, func() {
		cleanup2()
		cleanup()
	}, nil
}
